### ISSUE TITLE
Configure boat tracker

### ISSUE THREAD

**Issue by turnrye** [memhamwan/memhamwan.github.io#56]
- [ ] Build mast for the boat tracker and antenna
- [ ] Assemble mounting hardware
- [ ] Mount the powerbox
- [ ] build cable assembly for camera
- [ ] build cable assembly for connecting to existing mast

**Comment by turnrye** [comment]
This is done
