### ISSUE TITLE
Deploy boat tracker

### ISSUE THREAD

**Issue by turnrye** [memhamwan/memhamwan.github.io#60]
- [ ] Install the gland on the mast box
- [ ] Mount the webcam
- [ ] Plug the mast into the existing switch
- [ ] Mount the mast

**Comment by turnrye** [comment]
@seichold can you bring the cable gland? I can pack a step drill bit in order to drill the box. We'll just make the cable on the spot.

**Comment by turnrye** [comment]
This is done!
